spring:
  main:
    allow-circular-references: 'true'
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
      routes[2]:
        uri: http://localhost:8761
        filters[0]: SetPath=/
        id: discovery-server
        predicates[0]: Path=/eureka/web
      routes[0]:
        id: user-service
        uri: lb://user-service
        predicates[0]: Path=/api/user/**
      routes[3]:
        id: discovery-server-static
        predicates[0]: Path=/eureka/**
        uri: http://localhost:8761
      routes[1]:
        id: course-service
        predicates[0]: Path=/api/course/**
        uri: lb://course-service
  application:
    name: gateway-api
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: '30'
    lease-expiration-duration-in-seconds: '30'
ribbon:
  ConnectTimeout: '10000'
  ReadTimeout: '60000'
  eureka:
    enabled: 'true'
server:
  port: '8765'
